package persistencias;
// Generated 7/05/2018 09:33:50 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CivConceptos generated by hbm2java
 */
public class CivConceptos  implements java.io.Serializable {


     private BigDecimal conId;
     private CivTipoconcepto civTipoconcepto;
     private CivEstadoconceptos civEstadoconceptos;
     private String conNombre;
     private String conDescripcion;
     private BigDecimal conClase;
     private BigDecimal conPrioridad;
     private Date conFechainicial;
     private Date conFechafinal;
     private Set civDetalleDeudases = new HashSet(0);

    public CivConceptos() {
    }

	
    public CivConceptos(BigDecimal conId, CivTipoconcepto civTipoconcepto, CivEstadoconceptos civEstadoconceptos, String conNombre, Date conFechainicial) {
        this.conId = conId;
        this.civTipoconcepto = civTipoconcepto;
        this.civEstadoconceptos = civEstadoconceptos;
        this.conNombre = conNombre;
        this.conFechainicial = conFechainicial;
    }
    public CivConceptos(BigDecimal conId, CivTipoconcepto civTipoconcepto, CivEstadoconceptos civEstadoconceptos, String conNombre, String conDescripcion, BigDecimal conClase, BigDecimal conPrioridad, Date conFechainicial, Date conFechafinal, Set civDetalleDeudases) {
       this.conId = conId;
       this.civTipoconcepto = civTipoconcepto;
       this.civEstadoconceptos = civEstadoconceptos;
       this.conNombre = conNombre;
       this.conDescripcion = conDescripcion;
       this.conClase = conClase;
       this.conPrioridad = conPrioridad;
       this.conFechainicial = conFechainicial;
       this.conFechafinal = conFechafinal;
       this.civDetalleDeudases = civDetalleDeudases;
    }
   
    public BigDecimal getConId() {
        return this.conId;
    }
    
    public void setConId(BigDecimal conId) {
        this.conId = conId;
    }
    public CivTipoconcepto getCivTipoconcepto() {
        return this.civTipoconcepto;
    }
    
    public void setCivTipoconcepto(CivTipoconcepto civTipoconcepto) {
        this.civTipoconcepto = civTipoconcepto;
    }
    public CivEstadoconceptos getCivEstadoconceptos() {
        return this.civEstadoconceptos;
    }
    
    public void setCivEstadoconceptos(CivEstadoconceptos civEstadoconceptos) {
        this.civEstadoconceptos = civEstadoconceptos;
    }
    public String getConNombre() {
        return this.conNombre;
    }
    
    public void setConNombre(String conNombre) {
        this.conNombre = conNombre;
    }
    public String getConDescripcion() {
        return this.conDescripcion;
    }
    
    public void setConDescripcion(String conDescripcion) {
        this.conDescripcion = conDescripcion;
    }
    public BigDecimal getConClase() {
        return this.conClase;
    }
    
    public void setConClase(BigDecimal conClase) {
        this.conClase = conClase;
    }
    public BigDecimal getConPrioridad() {
        return this.conPrioridad;
    }
    
    public void setConPrioridad(BigDecimal conPrioridad) {
        this.conPrioridad = conPrioridad;
    }
    public Date getConFechainicial() {
        return this.conFechainicial;
    }
    
    public void setConFechainicial(Date conFechainicial) {
        this.conFechainicial = conFechainicial;
    }
    public Date getConFechafinal() {
        return this.conFechafinal;
    }
    
    public void setConFechafinal(Date conFechafinal) {
        this.conFechafinal = conFechafinal;
    }
    public Set getCivDetalleDeudases() {
        return this.civDetalleDeudases;
    }
    
    public void setCivDetalleDeudases(Set civDetalleDeudases) {
        this.civDetalleDeudases = civDetalleDeudases;
    }




}


