package persistencias;
// Generated 7/05/2018 09:33:50 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * CivDetalleRecUsuId generated by hbm2java
 */
public class CivDetalleRecUsuId  implements java.io.Serializable {


     private BigDecimal detRecId;
     private BigDecimal usuId;

    public CivDetalleRecUsuId() {
    }

    public CivDetalleRecUsuId(BigDecimal detRecId, BigDecimal usuId) {
       this.detRecId = detRecId;
       this.usuId = usuId;
    }
   
    public BigDecimal getDetRecId() {
        return this.detRecId;
    }
    
    public void setDetRecId(BigDecimal detRecId) {
        this.detRecId = detRecId;
    }
    public BigDecimal getUsuId() {
        return this.usuId;
    }
    
    public void setUsuId(BigDecimal usuId) {
        this.usuId = usuId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CivDetalleRecUsuId) ) return false;
		 CivDetalleRecUsuId castOther = ( CivDetalleRecUsuId ) other; 
         
		 return ( (this.getDetRecId()==castOther.getDetRecId()) || ( this.getDetRecId()!=null && castOther.getDetRecId()!=null && this.getDetRecId().equals(castOther.getDetRecId()) ) )
 && ( (this.getUsuId()==castOther.getUsuId()) || ( this.getUsuId()!=null && castOther.getUsuId()!=null && this.getUsuId().equals(castOther.getUsuId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getDetRecId() == null ? 0 : this.getDetRecId().hashCode() );
         result = 37 * result + ( getUsuId() == null ? 0 : this.getUsuId().hashCode() );
         return result;
   }   


}


