package persistencias;
// Generated 4/05/2018 09:28:55 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * CivDetalleRecursos generated by hbm2java
 */
public class CivDetalleRecursos  implements java.io.Serializable {


     private BigDecimal detRecId;
     private BigDecimal recId;
     private String detRecDescripcion;
     private String detRecObjeto;
     private String detRecTipo;
     private Set civDetalleRecUsus = new HashSet(0);

    public CivDetalleRecursos() {
    }

	
    public CivDetalleRecursos(BigDecimal detRecId) {
        this.detRecId = detRecId;
    }
    public CivDetalleRecursos(BigDecimal detRecId, BigDecimal recId, String detRecDescripcion, String detRecObjeto, String detRecTipo, Set civDetalleRecUsus) {
       this.detRecId = detRecId;
       this.recId = recId;
       this.detRecDescripcion = detRecDescripcion;
       this.detRecObjeto = detRecObjeto;
       this.detRecTipo = detRecTipo;
       this.civDetalleRecUsus = civDetalleRecUsus;
    }
   
    public BigDecimal getDetRecId() {
        return this.detRecId;
    }
    
    public void setDetRecId(BigDecimal detRecId) {
        this.detRecId = detRecId;
    }
    public BigDecimal getRecId() {
        return this.recId;
    }
    
    public void setRecId(BigDecimal recId) {
        this.recId = recId;
    }
    public String getDetRecDescripcion() {
        return this.detRecDescripcion;
    }
    
    public void setDetRecDescripcion(String detRecDescripcion) {
        this.detRecDescripcion = detRecDescripcion;
    }
    public String getDetRecObjeto() {
        return this.detRecObjeto;
    }
    
    public void setDetRecObjeto(String detRecObjeto) {
        this.detRecObjeto = detRecObjeto;
    }
    public String getDetRecTipo() {
        return this.detRecTipo;
    }
    
    public void setDetRecTipo(String detRecTipo) {
        this.detRecTipo = detRecTipo;
    }
    public Set getCivDetalleRecUsus() {
        return this.civDetalleRecUsus;
    }
    
    public void setCivDetalleRecUsus(Set civDetalleRecUsus) {
        this.civDetalleRecUsus = civDetalleRecUsus;
    }




}


