package persistencias;
// Generated 27/04/2018 03:42:45 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * CivDetalleProcesojuridico generated by hbm2java
 */
public class CivDetalleProcesojuridico  implements java.io.Serializable {


     private BigDecimal detprojuId;
     private CivUsuarios civUsuarios;
     private CivProcesosjuridicos civProcesosjuridicos;
     private BigDecimal detprojuTipo;
     private BigDecimal detprojuDiainicial;
     private BigDecimal detprojuDiafinal;
     private BigDecimal repId;
     private Boolean detprojuDireccion;
     private BigDecimal detprojuEstado;
     private Date detprojuFechainicial;
     private Date detprojuFechafinal;

    public CivDetalleProcesojuridico() {
    }

	
    public CivDetalleProcesojuridico(BigDecimal detprojuId) {
        this.detprojuId = detprojuId;
    }
    public CivDetalleProcesojuridico(BigDecimal detprojuId, CivUsuarios civUsuarios, CivProcesosjuridicos civProcesosjuridicos, BigDecimal detprojuTipo, BigDecimal detprojuDiainicial, BigDecimal detprojuDiafinal, BigDecimal repId, Boolean detprojuDireccion, BigDecimal detprojuEstado, Date detprojuFechainicial, Date detprojuFechafinal) {
       this.detprojuId = detprojuId;
       this.civUsuarios = civUsuarios;
       this.civProcesosjuridicos = civProcesosjuridicos;
       this.detprojuTipo = detprojuTipo;
       this.detprojuDiainicial = detprojuDiainicial;
       this.detprojuDiafinal = detprojuDiafinal;
       this.repId = repId;
       this.detprojuDireccion = detprojuDireccion;
       this.detprojuEstado = detprojuEstado;
       this.detprojuFechainicial = detprojuFechainicial;
       this.detprojuFechafinal = detprojuFechafinal;
    }
   
    public BigDecimal getDetprojuId() {
        return this.detprojuId;
    }
    
    public void setDetprojuId(BigDecimal detprojuId) {
        this.detprojuId = detprojuId;
    }
    public CivUsuarios getCivUsuarios() {
        return this.civUsuarios;
    }
    
    public void setCivUsuarios(CivUsuarios civUsuarios) {
        this.civUsuarios = civUsuarios;
    }
    public CivProcesosjuridicos getCivProcesosjuridicos() {
        return this.civProcesosjuridicos;
    }
    
    public void setCivProcesosjuridicos(CivProcesosjuridicos civProcesosjuridicos) {
        this.civProcesosjuridicos = civProcesosjuridicos;
    }
    public BigDecimal getDetprojuTipo() {
        return this.detprojuTipo;
    }
    
    public void setDetprojuTipo(BigDecimal detprojuTipo) {
        this.detprojuTipo = detprojuTipo;
    }
    public BigDecimal getDetprojuDiainicial() {
        return this.detprojuDiainicial;
    }
    
    public void setDetprojuDiainicial(BigDecimal detprojuDiainicial) {
        this.detprojuDiainicial = detprojuDiainicial;
    }
    public BigDecimal getDetprojuDiafinal() {
        return this.detprojuDiafinal;
    }
    
    public void setDetprojuDiafinal(BigDecimal detprojuDiafinal) {
        this.detprojuDiafinal = detprojuDiafinal;
    }
    public BigDecimal getRepId() {
        return this.repId;
    }
    
    public void setRepId(BigDecimal repId) {
        this.repId = repId;
    }
    public Boolean getDetprojuDireccion() {
        return this.detprojuDireccion;
    }
    
    public void setDetprojuDireccion(Boolean detprojuDireccion) {
        this.detprojuDireccion = detprojuDireccion;
    }
    public BigDecimal getDetprojuEstado() {
        return this.detprojuEstado;
    }
    
    public void setDetprojuEstado(BigDecimal detprojuEstado) {
        this.detprojuEstado = detprojuEstado;
    }
    public Date getDetprojuFechainicial() {
        return this.detprojuFechainicial;
    }
    
    public void setDetprojuFechainicial(Date detprojuFechainicial) {
        this.detprojuFechainicial = detprojuFechainicial;
    }
    public Date getDetprojuFechafinal() {
        return this.detprojuFechafinal;
    }
    
    public void setDetprojuFechafinal(Date detprojuFechafinal) {
        this.detprojuFechafinal = detprojuFechafinal;
    }




}


