package persistencias;
// Generated 17/04/2018 10:23:00 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * CivDatospersona generated by hbm2java
 */
public class CivDatospersona  implements java.io.Serializable {


     private BigDecimal datperId;
     private CivPersonas civPersonas;
     private CivTipodatopersona civTipodatopersona;
     private String datperDescripcion;
     private BigDecimal datperEstado;
     private Date datperFechainicial;
     private Date datperFechafinal;

    public CivDatospersona() {
    }

	
    public CivDatospersona(BigDecimal datperId, CivPersonas civPersonas, CivTipodatopersona civTipodatopersona, String datperDescripcion, BigDecimal datperEstado, Date datperFechainicial) {
        this.datperId = datperId;
        this.civPersonas = civPersonas;
        this.civTipodatopersona = civTipodatopersona;
        this.datperDescripcion = datperDescripcion;
        this.datperEstado = datperEstado;
        this.datperFechainicial = datperFechainicial;
    }
    public CivDatospersona(BigDecimal datperId, CivPersonas civPersonas, CivTipodatopersona civTipodatopersona, String datperDescripcion, BigDecimal datperEstado, Date datperFechainicial, Date datperFechafinal) {
       this.datperId = datperId;
       this.civPersonas = civPersonas;
       this.civTipodatopersona = civTipodatopersona;
       this.datperDescripcion = datperDescripcion;
       this.datperEstado = datperEstado;
       this.datperFechainicial = datperFechainicial;
       this.datperFechafinal = datperFechafinal;
    }
   
    public BigDecimal getDatperId() {
        return this.datperId;
    }
    
    public void setDatperId(BigDecimal datperId) {
        this.datperId = datperId;
    }
    public CivPersonas getCivPersonas() {
        return this.civPersonas;
    }
    
    public void setCivPersonas(CivPersonas civPersonas) {
        this.civPersonas = civPersonas;
    }
    public CivTipodatopersona getCivTipodatopersona() {
        return this.civTipodatopersona;
    }
    
    public void setCivTipodatopersona(CivTipodatopersona civTipodatopersona) {
        this.civTipodatopersona = civTipodatopersona;
    }
    public String getDatperDescripcion() {
        return this.datperDescripcion;
    }
    
    public void setDatperDescripcion(String datperDescripcion) {
        this.datperDescripcion = datperDescripcion;
    }
    public BigDecimal getDatperEstado() {
        return this.datperEstado;
    }
    
    public void setDatperEstado(BigDecimal datperEstado) {
        this.datperEstado = datperEstado;
    }
    public Date getDatperFechainicial() {
        return this.datperFechainicial;
    }
    
    public void setDatperFechainicial(Date datperFechainicial) {
        this.datperFechainicial = datperFechainicial;
    }
    public Date getDatperFechafinal() {
        return this.datperFechafinal;
    }
    
    public void setDatperFechafinal(Date datperFechafinal) {
        this.datperFechafinal = datperFechafinal;
    }




}


