package persistencias;
// Generated 7/05/2018 09:33:50 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * CivDatospersona generated by hbm2java
 */
public class CivDatospersona  implements java.io.Serializable {


     private BigDecimal datperId;
     private CivTipodatopersona civTipodatopersona;
     private CivPersonas civPersonas;
     private CivEstadodatospersona civEstadodatospersona;
     private String datperDescripcion;
     private Date datperFechainicial;
     private Date datperFechafinal;

    public CivDatospersona() {
    }

	
    public CivDatospersona(BigDecimal datperId, CivTipodatopersona civTipodatopersona, CivPersonas civPersonas, CivEstadodatospersona civEstadodatospersona, String datperDescripcion, Date datperFechainicial) {
        this.datperId = datperId;
        this.civTipodatopersona = civTipodatopersona;
        this.civPersonas = civPersonas;
        this.civEstadodatospersona = civEstadodatospersona;
        this.datperDescripcion = datperDescripcion;
        this.datperFechainicial = datperFechainicial;
    }
    public CivDatospersona(BigDecimal datperId, CivTipodatopersona civTipodatopersona, CivPersonas civPersonas, CivEstadodatospersona civEstadodatospersona, String datperDescripcion, Date datperFechainicial, Date datperFechafinal) {
       this.datperId = datperId;
       this.civTipodatopersona = civTipodatopersona;
       this.civPersonas = civPersonas;
       this.civEstadodatospersona = civEstadodatospersona;
       this.datperDescripcion = datperDescripcion;
       this.datperFechainicial = datperFechainicial;
       this.datperFechafinal = datperFechafinal;
    }
   
    public BigDecimal getDatperId() {
        return this.datperId;
    }
    
    public void setDatperId(BigDecimal datperId) {
        this.datperId = datperId;
    }
    public CivTipodatopersona getCivTipodatopersona() {
        return this.civTipodatopersona;
    }
    
    public void setCivTipodatopersona(CivTipodatopersona civTipodatopersona) {
        this.civTipodatopersona = civTipodatopersona;
    }
    public CivPersonas getCivPersonas() {
        return this.civPersonas;
    }
    
    public void setCivPersonas(CivPersonas civPersonas) {
        this.civPersonas = civPersonas;
    }
    public CivEstadodatospersona getCivEstadodatospersona() {
        return this.civEstadodatospersona;
    }
    
    public void setCivEstadodatospersona(CivEstadodatospersona civEstadodatospersona) {
        this.civEstadodatospersona = civEstadodatospersona;
    }
    public String getDatperDescripcion() {
        return this.datperDescripcion;
    }
    
    public void setDatperDescripcion(String datperDescripcion) {
        this.datperDescripcion = datperDescripcion;
    }
    public Date getDatperFechainicial() {
        return this.datperFechainicial;
    }
    
    public void setDatperFechainicial(Date datperFechainicial) {
        this.datperFechainicial = datperFechainicial;
    }
    public Date getDatperFechafinal() {
        return this.datperFechafinal;
    }
    
    public void setDatperFechafinal(Date datperFechafinal) {
        this.datperFechafinal = datperFechafinal;
    }




}


