package persistencias;
// Generated 27/04/2018 03:42:45 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * CivEstadotipoconcepto generated by hbm2java
 */
public class CivEstadotipoconcepto  implements java.io.Serializable {


     private BigDecimal esttipId;
     private String esttipDescripcion;
     private Date esttipFechainicial;
     private Date esttipFechafinal;

    public CivEstadotipoconcepto() {
    }

	
    public CivEstadotipoconcepto(BigDecimal esttipId) {
        this.esttipId = esttipId;
    }
    public CivEstadotipoconcepto(BigDecimal esttipId, String esttipDescripcion, Date esttipFechainicial, Date esttipFechafinal) {
       this.esttipId = esttipId;
       this.esttipDescripcion = esttipDescripcion;
       this.esttipFechainicial = esttipFechainicial;
       this.esttipFechafinal = esttipFechafinal;
    }
   
    public BigDecimal getEsttipId() {
        return this.esttipId;
    }
    
    public void setEsttipId(BigDecimal esttipId) {
        this.esttipId = esttipId;
    }
    public String getEsttipDescripcion() {
        return this.esttipDescripcion;
    }
    
    public void setEsttipDescripcion(String esttipDescripcion) {
        this.esttipDescripcion = esttipDescripcion;
    }
    public Date getEsttipFechainicial() {
        return this.esttipFechainicial;
    }
    
    public void setEsttipFechainicial(Date esttipFechainicial) {
        this.esttipFechainicial = esttipFechainicial;
    }
    public Date getEsttipFechafinal() {
        return this.esttipFechafinal;
    }
    
    public void setEsttipFechafinal(Date esttipFechafinal) {
        this.esttipFechafinal = esttipFechafinal;
    }




}


