package persistencias;
// Generated 4/05/2018 09:28:55 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CivEstadorecursos generated by hbm2java
 */
public class CivEstadorecursos  implements java.io.Serializable {


     private BigDecimal estrecId;
     private String estrecDescripcion;
     private Date estrecFechainicial;
     private Date estrecFechafinal;
     private Set civRecursoses = new HashSet(0);

    public CivEstadorecursos() {
    }

	
    public CivEstadorecursos(BigDecimal estrecId) {
        this.estrecId = estrecId;
    }
    public CivEstadorecursos(BigDecimal estrecId, String estrecDescripcion, Date estrecFechainicial, Date estrecFechafinal, Set civRecursoses) {
       this.estrecId = estrecId;
       this.estrecDescripcion = estrecDescripcion;
       this.estrecFechainicial = estrecFechainicial;
       this.estrecFechafinal = estrecFechafinal;
       this.civRecursoses = civRecursoses;
    }
   
    public BigDecimal getEstrecId() {
        return this.estrecId;
    }
    
    public void setEstrecId(BigDecimal estrecId) {
        this.estrecId = estrecId;
    }
    public String getEstrecDescripcion() {
        return this.estrecDescripcion;
    }
    
    public void setEstrecDescripcion(String estrecDescripcion) {
        this.estrecDescripcion = estrecDescripcion;
    }
    public Date getEstrecFechainicial() {
        return this.estrecFechainicial;
    }
    
    public void setEstrecFechainicial(Date estrecFechainicial) {
        this.estrecFechainicial = estrecFechainicial;
    }
    public Date getEstrecFechafinal() {
        return this.estrecFechafinal;
    }
    
    public void setEstrecFechafinal(Date estrecFechafinal) {
        this.estrecFechafinal = estrecFechafinal;
    }
    public Set getCivRecursoses() {
        return this.civRecursoses;
    }
    
    public void setCivRecursoses(Set civRecursoses) {
        this.civRecursoses = civRecursoses;
    }




}


