package persistencias;
// Generated 27/04/2018 03:42:45 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * CivEstadousuarios generated by hbm2java
 */
public class CivEstadousuarios  implements java.io.Serializable {


     private BigDecimal estusuId;
     private String estusuDescripcion;
     private Date estusuFechainicial;
     private Date estusuFechafinal;

    public CivEstadousuarios() {
    }

	
    public CivEstadousuarios(BigDecimal estusuId) {
        this.estusuId = estusuId;
    }
    public CivEstadousuarios(BigDecimal estusuId, String estusuDescripcion, Date estusuFechainicial, Date estusuFechafinal) {
       this.estusuId = estusuId;
       this.estusuDescripcion = estusuDescripcion;
       this.estusuFechainicial = estusuFechainicial;
       this.estusuFechafinal = estusuFechafinal;
    }
   
    public BigDecimal getEstusuId() {
        return this.estusuId;
    }
    
    public void setEstusuId(BigDecimal estusuId) {
        this.estusuId = estusuId;
    }
    public String getEstusuDescripcion() {
        return this.estusuDescripcion;
    }
    
    public void setEstusuDescripcion(String estusuDescripcion) {
        this.estusuDescripcion = estusuDescripcion;
    }
    public Date getEstusuFechainicial() {
        return this.estusuFechainicial;
    }
    
    public void setEstusuFechainicial(Date estusuFechainicial) {
        this.estusuFechainicial = estusuFechainicial;
    }
    public Date getEstusuFechafinal() {
        return this.estusuFechafinal;
    }
    
    public void setEstusuFechafinal(Date estusuFechafinal) {
        this.estusuFechafinal = estusuFechafinal;
    }




}


