package persistencias;
// Generated 27/04/2018 03:42:45 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * CivEstadodetalleProceso generated by hbm2java
 */
public class CivEstadodetalleProceso  implements java.io.Serializable {


     private BigDecimal estdetdeuId;
     private String estdetdeuDescripcion;
     private Date estdetdeuFechainicial;
     private Date estdetdeuFechafinal;

    public CivEstadodetalleProceso() {
    }

	
    public CivEstadodetalleProceso(BigDecimal estdetdeuId) {
        this.estdetdeuId = estdetdeuId;
    }
    public CivEstadodetalleProceso(BigDecimal estdetdeuId, String estdetdeuDescripcion, Date estdetdeuFechainicial, Date estdetdeuFechafinal) {
       this.estdetdeuId = estdetdeuId;
       this.estdetdeuDescripcion = estdetdeuDescripcion;
       this.estdetdeuFechainicial = estdetdeuFechainicial;
       this.estdetdeuFechafinal = estdetdeuFechafinal;
    }
   
    public BigDecimal getEstdetdeuId() {
        return this.estdetdeuId;
    }
    
    public void setEstdetdeuId(BigDecimal estdetdeuId) {
        this.estdetdeuId = estdetdeuId;
    }
    public String getEstdetdeuDescripcion() {
        return this.estdetdeuDescripcion;
    }
    
    public void setEstdetdeuDescripcion(String estdetdeuDescripcion) {
        this.estdetdeuDescripcion = estdetdeuDescripcion;
    }
    public Date getEstdetdeuFechainicial() {
        return this.estdetdeuFechainicial;
    }
    
    public void setEstdetdeuFechainicial(Date estdetdeuFechainicial) {
        this.estdetdeuFechainicial = estdetdeuFechainicial;
    }
    public Date getEstdetdeuFechafinal() {
        return this.estdetdeuFechafinal;
    }
    
    public void setEstdetdeuFechafinal(Date estdetdeuFechafinal) {
        this.estdetdeuFechafinal = estdetdeuFechafinal;
    }




}


