package persistencias;
// Generated 30/04/2018 08:39:48 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CivEstadodetalleDeudas generated by hbm2java
 */
public class CivEstadodetalleDeudas  implements java.io.Serializable {


     private BigDecimal estdetdeuId;
     private String estdetdeuDescripcion;
     private Date estdetdeuFechainicial;
     private Date estdetdeuFechafinal;
     private Set civDetalleDeudases = new HashSet(0);

    public CivEstadodetalleDeudas() {
    }

	
    public CivEstadodetalleDeudas(BigDecimal estdetdeuId) {
        this.estdetdeuId = estdetdeuId;
    }
    public CivEstadodetalleDeudas(BigDecimal estdetdeuId, String estdetdeuDescripcion, Date estdetdeuFechainicial, Date estdetdeuFechafinal, Set civDetalleDeudases) {
       this.estdetdeuId = estdetdeuId;
       this.estdetdeuDescripcion = estdetdeuDescripcion;
       this.estdetdeuFechainicial = estdetdeuFechainicial;
       this.estdetdeuFechafinal = estdetdeuFechafinal;
       this.civDetalleDeudases = civDetalleDeudases;
    }
   
    public BigDecimal getEstdetdeuId() {
        return this.estdetdeuId;
    }
    
    public void setEstdetdeuId(BigDecimal estdetdeuId) {
        this.estdetdeuId = estdetdeuId;
    }
    public String getEstdetdeuDescripcion() {
        return this.estdetdeuDescripcion;
    }
    
    public void setEstdetdeuDescripcion(String estdetdeuDescripcion) {
        this.estdetdeuDescripcion = estdetdeuDescripcion;
    }
    public Date getEstdetdeuFechainicial() {
        return this.estdetdeuFechainicial;
    }
    
    public void setEstdetdeuFechainicial(Date estdetdeuFechainicial) {
        this.estdetdeuFechainicial = estdetdeuFechainicial;
    }
    public Date getEstdetdeuFechafinal() {
        return this.estdetdeuFechafinal;
    }
    
    public void setEstdetdeuFechafinal(Date estdetdeuFechafinal) {
        this.estdetdeuFechafinal = estdetdeuFechafinal;
    }
    public Set getCivDetalleDeudases() {
        return this.civDetalleDeudases;
    }
    
    public void setCivDetalleDeudases(Set civDetalleDeudases) {
        this.civDetalleDeudases = civDetalleDeudases;
    }




}


