package persistencias;
// Generated 27/04/2018 03:42:45 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * CivEstadodetalleDeudas generated by hbm2java
 */
public class CivEstadodetalleDeudas  implements java.io.Serializable {


     private BigDecimal estdetId;
     private String estdetDescripcion;
     private Date estdetFechainicial;
     private Date estdetFechafinal;

    public CivEstadodetalleDeudas() {
    }

	
    public CivEstadodetalleDeudas(BigDecimal estdetId) {
        this.estdetId = estdetId;
    }
    public CivEstadodetalleDeudas(BigDecimal estdetId, String estdetDescripcion, Date estdetFechainicial, Date estdetFechafinal) {
       this.estdetId = estdetId;
       this.estdetDescripcion = estdetDescripcion;
       this.estdetFechainicial = estdetFechainicial;
       this.estdetFechafinal = estdetFechafinal;
    }
   
    public BigDecimal getEstdetId() {
        return this.estdetId;
    }
    
    public void setEstdetId(BigDecimal estdetId) {
        this.estdetId = estdetId;
    }
    public String getEstdetDescripcion() {
        return this.estdetDescripcion;
    }
    
    public void setEstdetDescripcion(String estdetDescripcion) {
        this.estdetDescripcion = estdetDescripcion;
    }
    public Date getEstdetFechainicial() {
        return this.estdetFechainicial;
    }
    
    public void setEstdetFechainicial(Date estdetFechainicial) {
        this.estdetFechainicial = estdetFechainicial;
    }
    public Date getEstdetFechafinal() {
        return this.estdetFechafinal;
    }
    
    public void setEstdetFechafinal(Date estdetFechafinal) {
        this.estdetFechafinal = estdetFechafinal;
    }




}


