package persistencias;
// Generated 27/04/2018 03:42:45 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * CivEstadouspHistoria generated by hbm2java
 */
public class CivEstadouspHistoria  implements java.io.Serializable {


     private BigDecimal estuspId;
     private String estuspDescripcion;
     private Date estuspFechainicial;
     private Date estuspFechafinal;

    public CivEstadouspHistoria() {
    }

	
    public CivEstadouspHistoria(BigDecimal estuspId) {
        this.estuspId = estuspId;
    }
    public CivEstadouspHistoria(BigDecimal estuspId, String estuspDescripcion, Date estuspFechainicial, Date estuspFechafinal) {
       this.estuspId = estuspId;
       this.estuspDescripcion = estuspDescripcion;
       this.estuspFechainicial = estuspFechainicial;
       this.estuspFechafinal = estuspFechafinal;
    }
   
    public BigDecimal getEstuspId() {
        return this.estuspId;
    }
    
    public void setEstuspId(BigDecimal estuspId) {
        this.estuspId = estuspId;
    }
    public String getEstuspDescripcion() {
        return this.estuspDescripcion;
    }
    
    public void setEstuspDescripcion(String estuspDescripcion) {
        this.estuspDescripcion = estuspDescripcion;
    }
    public Date getEstuspFechainicial() {
        return this.estuspFechainicial;
    }
    
    public void setEstuspFechainicial(Date estuspFechainicial) {
        this.estuspFechainicial = estuspFechainicial;
    }
    public Date getEstuspFechafinal() {
        return this.estuspFechafinal;
    }
    
    public void setEstuspFechafinal(Date estuspFechafinal) {
        this.estuspFechafinal = estuspFechafinal;
    }




}


