package persistencias;
// Generated 27/04/2018 03:42:45 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * CivEstadotipodatopersona generated by hbm2java
 */
public class CivEstadotipodatopersona  implements java.io.Serializable {


     private BigDecimal esttipdatId;
     private String esttipdatDescripcion;
     private Date esttipdatFechainicial;
     private Date esttipdatFechafinal;

    public CivEstadotipodatopersona() {
    }

	
    public CivEstadotipodatopersona(BigDecimal esttipdatId) {
        this.esttipdatId = esttipdatId;
    }
    public CivEstadotipodatopersona(BigDecimal esttipdatId, String esttipdatDescripcion, Date esttipdatFechainicial, Date esttipdatFechafinal) {
       this.esttipdatId = esttipdatId;
       this.esttipdatDescripcion = esttipdatDescripcion;
       this.esttipdatFechainicial = esttipdatFechainicial;
       this.esttipdatFechafinal = esttipdatFechafinal;
    }
   
    public BigDecimal getEsttipdatId() {
        return this.esttipdatId;
    }
    
    public void setEsttipdatId(BigDecimal esttipdatId) {
        this.esttipdatId = esttipdatId;
    }
    public String getEsttipdatDescripcion() {
        return this.esttipdatDescripcion;
    }
    
    public void setEsttipdatDescripcion(String esttipdatDescripcion) {
        this.esttipdatDescripcion = esttipdatDescripcion;
    }
    public Date getEsttipdatFechainicial() {
        return this.esttipdatFechainicial;
    }
    
    public void setEsttipdatFechainicial(Date esttipdatFechainicial) {
        this.esttipdatFechainicial = esttipdatFechainicial;
    }
    public Date getEsttipdatFechafinal() {
        return this.esttipdatFechafinal;
    }
    
    public void setEsttipdatFechafinal(Date esttipdatFechafinal) {
        this.esttipdatFechafinal = esttipdatFechafinal;
    }




}


