package persistencias;
// Generated 27/04/2018 03:42:45 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * CivEstadodeudas generated by hbm2java
 */
public class CivEstadodeudas  implements java.io.Serializable {


     private BigDecimal estdeuId;
     private String estdeuDescripcion;
     private Date estdeuFechainicial;
     private Date estdeuFechafinal;

    public CivEstadodeudas() {
    }

	
    public CivEstadodeudas(BigDecimal estdeuId) {
        this.estdeuId = estdeuId;
    }
    public CivEstadodeudas(BigDecimal estdeuId, String estdeuDescripcion, Date estdeuFechainicial, Date estdeuFechafinal) {
       this.estdeuId = estdeuId;
       this.estdeuDescripcion = estdeuDescripcion;
       this.estdeuFechainicial = estdeuFechainicial;
       this.estdeuFechafinal = estdeuFechafinal;
    }
   
    public BigDecimal getEstdeuId() {
        return this.estdeuId;
    }
    
    public void setEstdeuId(BigDecimal estdeuId) {
        this.estdeuId = estdeuId;
    }
    public String getEstdeuDescripcion() {
        return this.estdeuDescripcion;
    }
    
    public void setEstdeuDescripcion(String estdeuDescripcion) {
        this.estdeuDescripcion = estdeuDescripcion;
    }
    public Date getEstdeuFechainicial() {
        return this.estdeuFechainicial;
    }
    
    public void setEstdeuFechainicial(Date estdeuFechainicial) {
        this.estdeuFechainicial = estdeuFechainicial;
    }
    public Date getEstdeuFechafinal() {
        return this.estdeuFechafinal;
    }
    
    public void setEstdeuFechafinal(Date estdeuFechafinal) {
        this.estdeuFechafinal = estdeuFechafinal;
    }




}


