package persistencias;
// Generated 30/04/2018 08:39:48 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CivEstadodetalleProceso generated by hbm2java
 */
public class CivEstadodetalleProceso  implements java.io.Serializable {


     private BigDecimal estdetproId;
     private String estdetproDescripcion;
     private Date estdetproFechainicial;
     private Date estdetproFechafinal;
     private Set civDetalleProcesojuridicos = new HashSet(0);

    public CivEstadodetalleProceso() {
    }

	
    public CivEstadodetalleProceso(BigDecimal estdetproId) {
        this.estdetproId = estdetproId;
    }
    public CivEstadodetalleProceso(BigDecimal estdetproId, String estdetproDescripcion, Date estdetproFechainicial, Date estdetproFechafinal, Set civDetalleProcesojuridicos) {
       this.estdetproId = estdetproId;
       this.estdetproDescripcion = estdetproDescripcion;
       this.estdetproFechainicial = estdetproFechainicial;
       this.estdetproFechafinal = estdetproFechafinal;
       this.civDetalleProcesojuridicos = civDetalleProcesojuridicos;
    }
   
    public BigDecimal getEstdetproId() {
        return this.estdetproId;
    }
    
    public void setEstdetproId(BigDecimal estdetproId) {
        this.estdetproId = estdetproId;
    }
    public String getEstdetproDescripcion() {
        return this.estdetproDescripcion;
    }
    
    public void setEstdetproDescripcion(String estdetproDescripcion) {
        this.estdetproDescripcion = estdetproDescripcion;
    }
    public Date getEstdetproFechainicial() {
        return this.estdetproFechainicial;
    }
    
    public void setEstdetproFechainicial(Date estdetproFechainicial) {
        this.estdetproFechainicial = estdetproFechainicial;
    }
    public Date getEstdetproFechafinal() {
        return this.estdetproFechafinal;
    }
    
    public void setEstdetproFechafinal(Date estdetproFechafinal) {
        this.estdetproFechafinal = estdetproFechafinal;
    }
    public Set getCivDetalleProcesojuridicos() {
        return this.civDetalleProcesojuridicos;
    }
    
    public void setCivDetalleProcesojuridicos(Set civDetalleProcesojuridicos) {
        this.civDetalleProcesojuridicos = civDetalleProcesojuridicos;
    }




}


