package persistencias;
// Generated 27/04/2018 03:42:45 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * CivEstadoprocesojuridicos generated by hbm2java
 */
public class CivEstadoprocesojuridicos  implements java.io.Serializable {


     private BigDecimal estproId;
     private String estproDescripcion;
     private Date estproFechainicial;
     private Date estproFechafinal;

    public CivEstadoprocesojuridicos() {
    }

	
    public CivEstadoprocesojuridicos(BigDecimal estproId) {
        this.estproId = estproId;
    }
    public CivEstadoprocesojuridicos(BigDecimal estproId, String estproDescripcion, Date estproFechainicial, Date estproFechafinal) {
       this.estproId = estproId;
       this.estproDescripcion = estproDescripcion;
       this.estproFechainicial = estproFechainicial;
       this.estproFechafinal = estproFechafinal;
    }
   
    public BigDecimal getEstproId() {
        return this.estproId;
    }
    
    public void setEstproId(BigDecimal estproId) {
        this.estproId = estproId;
    }
    public String getEstproDescripcion() {
        return this.estproDescripcion;
    }
    
    public void setEstproDescripcion(String estproDescripcion) {
        this.estproDescripcion = estproDescripcion;
    }
    public Date getEstproFechainicial() {
        return this.estproFechainicial;
    }
    
    public void setEstproFechainicial(Date estproFechainicial) {
        this.estproFechainicial = estproFechainicial;
    }
    public Date getEstproFechafinal() {
        return this.estproFechafinal;
    }
    
    public void setEstproFechafinal(Date estproFechafinal) {
        this.estproFechafinal = estproFechafinal;
    }




}


