package persistencias;
// Generated 27/04/2018 03:42:45 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * CivEstadorecursos generated by hbm2java
 */
public class CivEstadorecursos  implements java.io.Serializable {


     private BigDecimal estrecId;
     private String estrecDescripcion;
     private Date estrecFechainicial;
     private Date estrecFechafinal;

    public CivEstadorecursos() {
    }

	
    public CivEstadorecursos(BigDecimal estrecId) {
        this.estrecId = estrecId;
    }
    public CivEstadorecursos(BigDecimal estrecId, String estrecDescripcion, Date estrecFechainicial, Date estrecFechafinal) {
       this.estrecId = estrecId;
       this.estrecDescripcion = estrecDescripcion;
       this.estrecFechainicial = estrecFechainicial;
       this.estrecFechafinal = estrecFechafinal;
    }
   
    public BigDecimal getEstrecId() {
        return this.estrecId;
    }
    
    public void setEstrecId(BigDecimal estrecId) {
        this.estrecId = estrecId;
    }
    public String getEstrecDescripcion() {
        return this.estrecDescripcion;
    }
    
    public void setEstrecDescripcion(String estrecDescripcion) {
        this.estrecDescripcion = estrecDescripcion;
    }
    public Date getEstrecFechainicial() {
        return this.estrecFechainicial;
    }
    
    public void setEstrecFechainicial(Date estrecFechainicial) {
        this.estrecFechainicial = estrecFechainicial;
    }
    public Date getEstrecFechafinal() {
        return this.estrecFechafinal;
    }
    
    public void setEstrecFechafinal(Date estrecFechafinal) {
        this.estrecFechafinal = estrecFechafinal;
    }




}


