package persistencias;
// Generated 3/05/2018 09:12:03 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CivEstadotipodocumentos generated by hbm2java
 */
public class CivEstadotipodocumentos  implements java.io.Serializable {


     private BigDecimal esttipdocId;
     private String esttipdocDescripcion;
     private Date esttipdocFechainicial;
     private Date esttipdocFechafinal;
     private Set civTipodocumentoses = new HashSet(0);

    public CivEstadotipodocumentos() {
    }

	
    public CivEstadotipodocumentos(BigDecimal esttipdocId) {
        this.esttipdocId = esttipdocId;
    }
    public CivEstadotipodocumentos(BigDecimal esttipdocId, String esttipdocDescripcion, Date esttipdocFechainicial, Date esttipdocFechafinal, Set civTipodocumentoses) {
       this.esttipdocId = esttipdocId;
       this.esttipdocDescripcion = esttipdocDescripcion;
       this.esttipdocFechainicial = esttipdocFechainicial;
       this.esttipdocFechafinal = esttipdocFechafinal;
       this.civTipodocumentoses = civTipodocumentoses;
    }
   
    public BigDecimal getEsttipdocId() {
        return this.esttipdocId;
    }
    
    public void setEsttipdocId(BigDecimal esttipdocId) {
        this.esttipdocId = esttipdocId;
    }
    public String getEsttipdocDescripcion() {
        return this.esttipdocDescripcion;
    }
    
    public void setEsttipdocDescripcion(String esttipdocDescripcion) {
        this.esttipdocDescripcion = esttipdocDescripcion;
    }
    public Date getEsttipdocFechainicial() {
        return this.esttipdocFechainicial;
    }
    
    public void setEsttipdocFechainicial(Date esttipdocFechainicial) {
        this.esttipdocFechainicial = esttipdocFechainicial;
    }
    public Date getEsttipdocFechafinal() {
        return this.esttipdocFechafinal;
    }
    
    public void setEsttipdocFechafinal(Date esttipdocFechafinal) {
        this.esttipdocFechafinal = esttipdocFechafinal;
    }
    public Set getCivTipodocumentoses() {
        return this.civTipodocumentoses;
    }
    
    public void setCivTipodocumentoses(Set civTipodocumentoses) {
        this.civTipodocumentoses = civTipodocumentoses;
    }




}


