package persistencias;
// Generated 27/04/2018 03:42:45 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * CivEstadoconceptos generated by hbm2java
 */
public class CivEstadoconceptos  implements java.io.Serializable {


     private BigDecimal estconId;
     private String estconDescripcion;
     private Date estconFechainicial;
     private Date estconFechafinal;

    public CivEstadoconceptos() {
    }

	
    public CivEstadoconceptos(BigDecimal estconId) {
        this.estconId = estconId;
    }
    public CivEstadoconceptos(BigDecimal estconId, String estconDescripcion, Date estconFechainicial, Date estconFechafinal) {
       this.estconId = estconId;
       this.estconDescripcion = estconDescripcion;
       this.estconFechainicial = estconFechainicial;
       this.estconFechafinal = estconFechafinal;
    }
   
    public BigDecimal getEstconId() {
        return this.estconId;
    }
    
    public void setEstconId(BigDecimal estconId) {
        this.estconId = estconId;
    }
    public String getEstconDescripcion() {
        return this.estconDescripcion;
    }
    
    public void setEstconDescripcion(String estconDescripcion) {
        this.estconDescripcion = estconDescripcion;
    }
    public Date getEstconFechainicial() {
        return this.estconFechainicial;
    }
    
    public void setEstconFechainicial(Date estconFechainicial) {
        this.estconFechainicial = estconFechainicial;
    }
    public Date getEstconFechafinal() {
        return this.estconFechafinal;
    }
    
    public void setEstconFechafinal(Date estconFechafinal) {
        this.estconFechafinal = estconFechafinal;
    }




}


