package persistencias;
// Generated 27/04/2018 03:42:45 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * CivEstadoerrores generated by hbm2java
 */
public class CivEstadoerrores  implements java.io.Serializable {


     private BigDecimal esterrId;
     private String esterrDescripcion;
     private Date esterrFechainicial;
     private Date esterrFechafinal;

    public CivEstadoerrores() {
    }

	
    public CivEstadoerrores(BigDecimal esterrId) {
        this.esterrId = esterrId;
    }
    public CivEstadoerrores(BigDecimal esterrId, String esterrDescripcion, Date esterrFechainicial, Date esterrFechafinal) {
       this.esterrId = esterrId;
       this.esterrDescripcion = esterrDescripcion;
       this.esterrFechainicial = esterrFechainicial;
       this.esterrFechafinal = esterrFechafinal;
    }
   
    public BigDecimal getEsterrId() {
        return this.esterrId;
    }
    
    public void setEsterrId(BigDecimal esterrId) {
        this.esterrId = esterrId;
    }
    public String getEsterrDescripcion() {
        return this.esterrDescripcion;
    }
    
    public void setEsterrDescripcion(String esterrDescripcion) {
        this.esterrDescripcion = esterrDescripcion;
    }
    public Date getEsterrFechainicial() {
        return this.esterrFechainicial;
    }
    
    public void setEsterrFechainicial(Date esterrFechainicial) {
        this.esterrFechainicial = esterrFechainicial;
    }
    public Date getEsterrFechafinal() {
        return this.esterrFechafinal;
    }
    
    public void setEsterrFechafinal(Date esterrFechafinal) {
        this.esterrFechafinal = esterrFechafinal;
    }




}


