package persistencias;
// Generated 3/05/2018 09:12:03 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CivEstadoprocesojuridicos generated by hbm2java
 */
public class CivEstadoprocesojuridicos  implements java.io.Serializable {


     private BigDecimal estproId;
     private String estproDescripcion;
     private Date estproFechainicial;
     private Date estproFechafinal;
     private Set civProcesosjuridicoses = new HashSet(0);

    public CivEstadoprocesojuridicos() {
    }

	
    public CivEstadoprocesojuridicos(BigDecimal estproId) {
        this.estproId = estproId;
    }
    public CivEstadoprocesojuridicos(BigDecimal estproId, String estproDescripcion, Date estproFechainicial, Date estproFechafinal, Set civProcesosjuridicoses) {
       this.estproId = estproId;
       this.estproDescripcion = estproDescripcion;
       this.estproFechainicial = estproFechainicial;
       this.estproFechafinal = estproFechafinal;
       this.civProcesosjuridicoses = civProcesosjuridicoses;
    }
   
    public BigDecimal getEstproId() {
        return this.estproId;
    }
    
    public void setEstproId(BigDecimal estproId) {
        this.estproId = estproId;
    }
    public String getEstproDescripcion() {
        return this.estproDescripcion;
    }
    
    public void setEstproDescripcion(String estproDescripcion) {
        this.estproDescripcion = estproDescripcion;
    }
    public Date getEstproFechainicial() {
        return this.estproFechainicial;
    }
    
    public void setEstproFechainicial(Date estproFechainicial) {
        this.estproFechainicial = estproFechainicial;
    }
    public Date getEstproFechafinal() {
        return this.estproFechafinal;
    }
    
    public void setEstproFechafinal(Date estproFechafinal) {
        this.estproFechafinal = estproFechafinal;
    }
    public Set getCivProcesosjuridicoses() {
        return this.civProcesosjuridicoses;
    }
    
    public void setCivProcesosjuridicoses(Set civProcesosjuridicoses) {
        this.civProcesosjuridicoses = civProcesosjuridicoses;
    }




}


