package persistencias;
// Generated 27/04/2018 03:42:45 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * CivEstadoperfilesrecurso generated by hbm2java
 */
public class CivEstadoperfilesrecurso  implements java.io.Serializable {


     private BigDecimal estperrecId;
     private String estperrecDescripcion;
     private Date estperrecFechainicial;
     private Date estperrecFechafinal;

    public CivEstadoperfilesrecurso() {
    }

	
    public CivEstadoperfilesrecurso(BigDecimal estperrecId) {
        this.estperrecId = estperrecId;
    }
    public CivEstadoperfilesrecurso(BigDecimal estperrecId, String estperrecDescripcion, Date estperrecFechainicial, Date estperrecFechafinal) {
       this.estperrecId = estperrecId;
       this.estperrecDescripcion = estperrecDescripcion;
       this.estperrecFechainicial = estperrecFechainicial;
       this.estperrecFechafinal = estperrecFechafinal;
    }
   
    public BigDecimal getEstperrecId() {
        return this.estperrecId;
    }
    
    public void setEstperrecId(BigDecimal estperrecId) {
        this.estperrecId = estperrecId;
    }
    public String getEstperrecDescripcion() {
        return this.estperrecDescripcion;
    }
    
    public void setEstperrecDescripcion(String estperrecDescripcion) {
        this.estperrecDescripcion = estperrecDescripcion;
    }
    public Date getEstperrecFechainicial() {
        return this.estperrecFechainicial;
    }
    
    public void setEstperrecFechainicial(Date estperrecFechainicial) {
        this.estperrecFechainicial = estperrecFechainicial;
    }
    public Date getEstperrecFechafinal() {
        return this.estperrecFechafinal;
    }
    
    public void setEstperrecFechafinal(Date estperrecFechafinal) {
        this.estperrecFechafinal = estperrecFechafinal;
    }




}


