package persistencias;
// Generated 27/04/2018 03:42:45 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * CivEstadotiporecursos generated by hbm2java
 */
public class CivEstadotiporecursos  implements java.io.Serializable {


     private BigDecimal esttiprecId;
     private String esttiprecDescripcion;
     private Date esttiprecFechainicial;
     private Date esttiprecFechafinal;

    public CivEstadotiporecursos() {
    }

	
    public CivEstadotiporecursos(BigDecimal esttiprecId) {
        this.esttiprecId = esttiprecId;
    }
    public CivEstadotiporecursos(BigDecimal esttiprecId, String esttiprecDescripcion, Date esttiprecFechainicial, Date esttiprecFechafinal) {
       this.esttiprecId = esttiprecId;
       this.esttiprecDescripcion = esttiprecDescripcion;
       this.esttiprecFechainicial = esttiprecFechainicial;
       this.esttiprecFechafinal = esttiprecFechafinal;
    }
   
    public BigDecimal getEsttiprecId() {
        return this.esttiprecId;
    }
    
    public void setEsttiprecId(BigDecimal esttiprecId) {
        this.esttiprecId = esttiprecId;
    }
    public String getEsttiprecDescripcion() {
        return this.esttiprecDescripcion;
    }
    
    public void setEsttiprecDescripcion(String esttiprecDescripcion) {
        this.esttiprecDescripcion = esttiprecDescripcion;
    }
    public Date getEsttiprecFechainicial() {
        return this.esttiprecFechainicial;
    }
    
    public void setEsttiprecFechainicial(Date esttiprecFechainicial) {
        this.esttiprecFechainicial = esttiprecFechainicial;
    }
    public Date getEsttiprecFechafinal() {
        return this.esttiprecFechafinal;
    }
    
    public void setEsttiprecFechafinal(Date esttiprecFechafinal) {
        this.esttiprecFechafinal = esttiprecFechafinal;
    }




}


