package persistencias;
// Generated 27/04/2018 03:42:45 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * CivEstadoperfiles generated by hbm2java
 */
public class CivEstadoperfiles  implements java.io.Serializable {


     private BigDecimal estperId;
     private String estperDescripcion;
     private Date estperFechainicial;
     private Date estperFechafinal;

    public CivEstadoperfiles() {
    }

	
    public CivEstadoperfiles(BigDecimal estperId) {
        this.estperId = estperId;
    }
    public CivEstadoperfiles(BigDecimal estperId, String estperDescripcion, Date estperFechainicial, Date estperFechafinal) {
       this.estperId = estperId;
       this.estperDescripcion = estperDescripcion;
       this.estperFechainicial = estperFechainicial;
       this.estperFechafinal = estperFechafinal;
    }
   
    public BigDecimal getEstperId() {
        return this.estperId;
    }
    
    public void setEstperId(BigDecimal estperId) {
        this.estperId = estperId;
    }
    public String getEstperDescripcion() {
        return this.estperDescripcion;
    }
    
    public void setEstperDescripcion(String estperDescripcion) {
        this.estperDescripcion = estperDescripcion;
    }
    public Date getEstperFechainicial() {
        return this.estperFechainicial;
    }
    
    public void setEstperFechainicial(Date estperFechainicial) {
        this.estperFechainicial = estperFechainicial;
    }
    public Date getEstperFechafinal() {
        return this.estperFechafinal;
    }
    
    public void setEstperFechafinal(Date estperFechafinal) {
        this.estperFechafinal = estperFechafinal;
    }




}


