package persistencias;
// Generated 27/04/2018 03:42:45 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * CivEstadotipodocumentos generated by hbm2java
 */
public class CivEstadotipodocumentos  implements java.io.Serializable {


     private BigDecimal esttipdecId;
     private String esttipdecDescripcion;
     private Date esttipdecFechainicial;
     private Date esttipdecFechafinal;

    public CivEstadotipodocumentos() {
    }

	
    public CivEstadotipodocumentos(BigDecimal esttipdecId) {
        this.esttipdecId = esttipdecId;
    }
    public CivEstadotipodocumentos(BigDecimal esttipdecId, String esttipdecDescripcion, Date esttipdecFechainicial, Date esttipdecFechafinal) {
       this.esttipdecId = esttipdecId;
       this.esttipdecDescripcion = esttipdecDescripcion;
       this.esttipdecFechainicial = esttipdecFechainicial;
       this.esttipdecFechafinal = esttipdecFechafinal;
    }
   
    public BigDecimal getEsttipdecId() {
        return this.esttipdecId;
    }
    
    public void setEsttipdecId(BigDecimal esttipdecId) {
        this.esttipdecId = esttipdecId;
    }
    public String getEsttipdecDescripcion() {
        return this.esttipdecDescripcion;
    }
    
    public void setEsttipdecDescripcion(String esttipdecDescripcion) {
        this.esttipdecDescripcion = esttipdecDescripcion;
    }
    public Date getEsttipdecFechainicial() {
        return this.esttipdecFechainicial;
    }
    
    public void setEsttipdecFechainicial(Date esttipdecFechainicial) {
        this.esttipdecFechainicial = esttipdecFechainicial;
    }
    public Date getEsttipdecFechafinal() {
        return this.esttipdecFechafinal;
    }
    
    public void setEsttipdecFechafinal(Date esttipdecFechafinal) {
        this.esttipdecFechafinal = esttipdecFechafinal;
    }




}


