package persistencias;
// Generated 27/04/2018 03:42:45 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * CivEstadoattempts generated by hbm2java
 */
public class CivEstadoattempts  implements java.io.Serializable {


     private BigDecimal estattId;
     private String estattDescripcion;
     private Date estattFechainicial;
     private Date estaattFechafinal;

    public CivEstadoattempts() {
    }

	
    public CivEstadoattempts(BigDecimal estattId) {
        this.estattId = estattId;
    }
    public CivEstadoattempts(BigDecimal estattId, String estattDescripcion, Date estattFechainicial, Date estaattFechafinal) {
       this.estattId = estattId;
       this.estattDescripcion = estattDescripcion;
       this.estattFechainicial = estattFechainicial;
       this.estaattFechafinal = estaattFechafinal;
    }
   
    public BigDecimal getEstattId() {
        return this.estattId;
    }
    
    public void setEstattId(BigDecimal estattId) {
        this.estattId = estattId;
    }
    public String getEstattDescripcion() {
        return this.estattDescripcion;
    }
    
    public void setEstattDescripcion(String estattDescripcion) {
        this.estattDescripcion = estattDescripcion;
    }
    public Date getEstattFechainicial() {
        return this.estattFechainicial;
    }
    
    public void setEstattFechainicial(Date estattFechainicial) {
        this.estattFechainicial = estattFechainicial;
    }
    public Date getEstaattFechafinal() {
        return this.estaattFechafinal;
    }
    
    public void setEstaattFechafinal(Date estaattFechafinal) {
        this.estaattFechafinal = estaattFechafinal;
    }




}


