package persistencias;
// Generated 27/04/2018 03:42:45 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * CivEstadologEventos generated by hbm2java
 */
public class CivEstadologEventos  implements java.io.Serializable {


     private BigDecimal estlogId;
     private String estlogDescripcion;
     private Date estlogFechainicial;
     private Date estlogFechafinal;

    public CivEstadologEventos() {
    }

	
    public CivEstadologEventos(BigDecimal estlogId) {
        this.estlogId = estlogId;
    }
    public CivEstadologEventos(BigDecimal estlogId, String estlogDescripcion, Date estlogFechainicial, Date estlogFechafinal) {
       this.estlogId = estlogId;
       this.estlogDescripcion = estlogDescripcion;
       this.estlogFechainicial = estlogFechainicial;
       this.estlogFechafinal = estlogFechafinal;
    }
   
    public BigDecimal getEstlogId() {
        return this.estlogId;
    }
    
    public void setEstlogId(BigDecimal estlogId) {
        this.estlogId = estlogId;
    }
    public String getEstlogDescripcion() {
        return this.estlogDescripcion;
    }
    
    public void setEstlogDescripcion(String estlogDescripcion) {
        this.estlogDescripcion = estlogDescripcion;
    }
    public Date getEstlogFechainicial() {
        return this.estlogFechainicial;
    }
    
    public void setEstlogFechainicial(Date estlogFechainicial) {
        this.estlogFechainicial = estlogFechainicial;
    }
    public Date getEstlogFechafinal() {
        return this.estlogFechafinal;
    }
    
    public void setEstlogFechafinal(Date estlogFechafinal) {
        this.estlogFechafinal = estlogFechafinal;
    }




}


