package persistencias;
// Generated 27/04/2018 03:42:45 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * CivEstadohistorialPerfil generated by hbm2java
 */
public class CivEstadohistorialPerfil  implements java.io.Serializable {


     private BigDecimal esthisId;
     private String esthisDescripcion;
     private Date esthisFechainicial;
     private Date esthisFechafinal;

    public CivEstadohistorialPerfil() {
    }

	
    public CivEstadohistorialPerfil(BigDecimal esthisId) {
        this.esthisId = esthisId;
    }
    public CivEstadohistorialPerfil(BigDecimal esthisId, String esthisDescripcion, Date esthisFechainicial, Date esthisFechafinal) {
       this.esthisId = esthisId;
       this.esthisDescripcion = esthisDescripcion;
       this.esthisFechainicial = esthisFechainicial;
       this.esthisFechafinal = esthisFechafinal;
    }
   
    public BigDecimal getEsthisId() {
        return this.esthisId;
    }
    
    public void setEsthisId(BigDecimal esthisId) {
        this.esthisId = esthisId;
    }
    public String getEsthisDescripcion() {
        return this.esthisDescripcion;
    }
    
    public void setEsthisDescripcion(String esthisDescripcion) {
        this.esthisDescripcion = esthisDescripcion;
    }
    public Date getEsthisFechainicial() {
        return this.esthisFechainicial;
    }
    
    public void setEsthisFechainicial(Date esthisFechainicial) {
        this.esthisFechainicial = esthisFechainicial;
    }
    public Date getEsthisFechafinal() {
        return this.esthisFechafinal;
    }
    
    public void setEsthisFechafinal(Date esthisFechafinal) {
        this.esthisFechafinal = esthisFechafinal;
    }




}


