package persistencias;
// Generated 4/05/2018 09:28:55 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * CivEstadosparametricos generated by hbm2java
 */
public class CivEstadosparametricos  implements java.io.Serializable {


     private BigDecimal estparId;
     private String estparNombretabla;
     private String estparNombre;
     private Date estparFechainicial;
     private Date estparFechafinal;

    public CivEstadosparametricos() {
    }

	
    public CivEstadosparametricos(BigDecimal estparId) {
        this.estparId = estparId;
    }
    public CivEstadosparametricos(BigDecimal estparId, String estparNombretabla, String estparNombre, Date estparFechainicial, Date estparFechafinal) {
       this.estparId = estparId;
       this.estparNombretabla = estparNombretabla;
       this.estparNombre = estparNombre;
       this.estparFechainicial = estparFechainicial;
       this.estparFechafinal = estparFechafinal;
    }
   
    public BigDecimal getEstparId() {
        return this.estparId;
    }
    
    public void setEstparId(BigDecimal estparId) {
        this.estparId = estparId;
    }
    public String getEstparNombretabla() {
        return this.estparNombretabla;
    }
    
    public void setEstparNombretabla(String estparNombretabla) {
        this.estparNombretabla = estparNombretabla;
    }
    public String getEstparNombre() {
        return this.estparNombre;
    }
    
    public void setEstparNombre(String estparNombre) {
        this.estparNombre = estparNombre;
    }
    public Date getEstparFechainicial() {
        return this.estparFechainicial;
    }
    
    public void setEstparFechainicial(Date estparFechainicial) {
        this.estparFechainicial = estparFechainicial;
    }
    public Date getEstparFechafinal() {
        return this.estparFechafinal;
    }
    
    public void setEstparFechafinal(Date estparFechafinal) {
        this.estparFechafinal = estparFechafinal;
    }




}


