package persistencias;
// Generated 4/05/2018 09:28:55 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CivEstadotipodeuda generated by hbm2java
 */
public class CivEstadotipodeuda  implements java.io.Serializable {


     private BigDecimal esttipdeuId;
     private String esttipdeuDescripcion;
     private Date esttipdeuFechainicial;
     private Date esttipdeuFechafinal;
     private Set civTipodeudas = new HashSet(0);

    public CivEstadotipodeuda() {
    }

	
    public CivEstadotipodeuda(BigDecimal esttipdeuId) {
        this.esttipdeuId = esttipdeuId;
    }
    public CivEstadotipodeuda(BigDecimal esttipdeuId, String esttipdeuDescripcion, Date esttipdeuFechainicial, Date esttipdeuFechafinal, Set civTipodeudas) {
       this.esttipdeuId = esttipdeuId;
       this.esttipdeuDescripcion = esttipdeuDescripcion;
       this.esttipdeuFechainicial = esttipdeuFechainicial;
       this.esttipdeuFechafinal = esttipdeuFechafinal;
       this.civTipodeudas = civTipodeudas;
    }
   
    public BigDecimal getEsttipdeuId() {
        return this.esttipdeuId;
    }
    
    public void setEsttipdeuId(BigDecimal esttipdeuId) {
        this.esttipdeuId = esttipdeuId;
    }
    public String getEsttipdeuDescripcion() {
        return this.esttipdeuDescripcion;
    }
    
    public void setEsttipdeuDescripcion(String esttipdeuDescripcion) {
        this.esttipdeuDescripcion = esttipdeuDescripcion;
    }
    public Date getEsttipdeuFechainicial() {
        return this.esttipdeuFechainicial;
    }
    
    public void setEsttipdeuFechainicial(Date esttipdeuFechainicial) {
        this.esttipdeuFechainicial = esttipdeuFechainicial;
    }
    public Date getEsttipdeuFechafinal() {
        return this.esttipdeuFechafinal;
    }
    
    public void setEsttipdeuFechafinal(Date esttipdeuFechafinal) {
        this.esttipdeuFechafinal = esttipdeuFechafinal;
    }
    public Set getCivTipodeudas() {
        return this.civTipodeudas;
    }
    
    public void setCivTipodeudas(Set civTipodeudas) {
        this.civTipodeudas = civTipodeudas;
    }




}


