package persistencias;
// Generated 7/05/2018 09:33:50 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CivEstadomovimiento generated by hbm2java
 */
public class CivEstadomovimiento  implements java.io.Serializable {


     private BigDecimal estmoviId;
     private String estmoviDescripcion;
     private Date column1;
     private Date estmoviFechafinal;
     private Set civMovimientoses = new HashSet(0);

    public CivEstadomovimiento() {
    }

	
    public CivEstadomovimiento(BigDecimal estmoviId) {
        this.estmoviId = estmoviId;
    }
    public CivEstadomovimiento(BigDecimal estmoviId, String estmoviDescripcion, Date column1, Date estmoviFechafinal, Set civMovimientoses) {
       this.estmoviId = estmoviId;
       this.estmoviDescripcion = estmoviDescripcion;
       this.column1 = column1;
       this.estmoviFechafinal = estmoviFechafinal;
       this.civMovimientoses = civMovimientoses;
    }
   
    public BigDecimal getEstmoviId() {
        return this.estmoviId;
    }
    
    public void setEstmoviId(BigDecimal estmoviId) {
        this.estmoviId = estmoviId;
    }
    public String getEstmoviDescripcion() {
        return this.estmoviDescripcion;
    }
    
    public void setEstmoviDescripcion(String estmoviDescripcion) {
        this.estmoviDescripcion = estmoviDescripcion;
    }
    public Date getColumn1() {
        return this.column1;
    }
    
    public void setColumn1(Date column1) {
        this.column1 = column1;
    }
    public Date getEstmoviFechafinal() {
        return this.estmoviFechafinal;
    }
    
    public void setEstmoviFechafinal(Date estmoviFechafinal) {
        this.estmoviFechafinal = estmoviFechafinal;
    }
    public Set getCivMovimientoses() {
        return this.civMovimientoses;
    }
    
    public void setCivMovimientoses(Set civMovimientoses) {
        this.civMovimientoses = civMovimientoses;
    }




}


