package persistencias;
// Generated 7/05/2018 09:33:50 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CivEstadotipoconcepto generated by hbm2java
 */
public class CivEstadotipoconcepto  implements java.io.Serializable {


     private BigDecimal esttipconId;
     private String esttipconDescripcion;
     private Date esttipconFechainicial;
     private Date esttipconFechafinal;
     private Set civTipoconceptos = new HashSet(0);

    public CivEstadotipoconcepto() {
    }

	
    public CivEstadotipoconcepto(BigDecimal esttipconId) {
        this.esttipconId = esttipconId;
    }
    public CivEstadotipoconcepto(BigDecimal esttipconId, String esttipconDescripcion, Date esttipconFechainicial, Date esttipconFechafinal, Set civTipoconceptos) {
       this.esttipconId = esttipconId;
       this.esttipconDescripcion = esttipconDescripcion;
       this.esttipconFechainicial = esttipconFechainicial;
       this.esttipconFechafinal = esttipconFechafinal;
       this.civTipoconceptos = civTipoconceptos;
    }
   
    public BigDecimal getEsttipconId() {
        return this.esttipconId;
    }
    
    public void setEsttipconId(BigDecimal esttipconId) {
        this.esttipconId = esttipconId;
    }
    public String getEsttipconDescripcion() {
        return this.esttipconDescripcion;
    }
    
    public void setEsttipconDescripcion(String esttipconDescripcion) {
        this.esttipconDescripcion = esttipconDescripcion;
    }
    public Date getEsttipconFechainicial() {
        return this.esttipconFechainicial;
    }
    
    public void setEsttipconFechainicial(Date esttipconFechainicial) {
        this.esttipconFechainicial = esttipconFechainicial;
    }
    public Date getEsttipconFechafinal() {
        return this.esttipconFechafinal;
    }
    
    public void setEsttipconFechafinal(Date esttipconFechafinal) {
        this.esttipconFechafinal = esttipconFechafinal;
    }
    public Set getCivTipoconceptos() {
        return this.civTipoconceptos;
    }
    
    public void setCivTipoconceptos(Set civTipoconceptos) {
        this.civTipoconceptos = civTipoconceptos;
    }




}


