package persistencias;
// Generated 7/05/2018 09:33:50 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * CivMovimientos generated by hbm2java
 */
public class CivMovimientos  implements java.io.Serializable {


     private BigDecimal movId;
     private CivEstadomovimiento civEstadomovimiento;
     private BigDecimal deuId;
     private BigDecimal detpropId;
     private Date fechaInicial;
     private Date fechaFinal;
     private BigDecimal usuId;
     
    public CivMovimientos() {
    }

	
    public CivMovimientos(BigDecimal movId, CivEstadomovimiento civEstadomovimiento,  BigDecimal usuId) {
        this.movId = movId;
        this.civEstadomovimiento = civEstadomovimiento;
        this.usuId = usuId;
        
    }
    public CivMovimientos(BigDecimal movId, CivEstadomovimiento civEstadomovimiento, BigDecimal deuId, BigDecimal detpropId, Date fechaInicial, Date fechaFinal, BigDecimal usuId) {
       this.movId = movId;
       this.civEstadomovimiento = civEstadomovimiento;
       this.deuId = deuId;
       this.detpropId = detpropId;
       this.fechaInicial = fechaInicial;
       this.fechaFinal = fechaFinal;
       this.usuId = usuId;
       
    }
   
    public BigDecimal getMovId() {
        return this.movId;
    }
    
    public void setMovId(BigDecimal movId) {
        this.movId = movId;
    }
    public CivEstadomovimiento getCivEstadomovimiento() {
        return this.civEstadomovimiento;
    }
    
    public void setCivEstadomovimiento(CivEstadomovimiento civEstadomovimiento) {
        this.civEstadomovimiento = civEstadomovimiento;
    }
    public BigDecimal getDeuId() {
        return this.deuId;
    }
    
    public void setDeuId(BigDecimal deuId) {
        this.deuId = deuId;
    }
    public BigDecimal getDetpropId() {
        return this.detpropId;
    }
    
    public void setDetpropId(BigDecimal detpropId) {
        this.detpropId = detpropId;
    }
    public Date getFechaInicial() {
        return this.fechaInicial;
    }
    
    public void setFechaInicial(Date fechaInicial) {
        this.fechaInicial = fechaInicial;
    }
    public Date getFechaFinal() {
        return this.fechaFinal;
    }
    
    public void setFechaFinal(Date fechaFinal) {
        this.fechaFinal = fechaFinal;
    }
    public BigDecimal getUsuId() {
        return this.usuId;
    }
    
    public void setUsuId(BigDecimal usuId) {
        this.usuId = usuId;
    }

   



}


