package persistencias;
// Generated 17/04/2018 10:23:00 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * CivPerfilrecurso generated by hbm2java
 */
public class CivPerfilrecurso  implements java.io.Serializable {


     private CivPerfilrecursoId id;
     private CivRecursos civRecursos;
     private CivUsuarios civUsuarios;
     private Date perrecFechaini;
     private Date perrecFechafin;

    public CivPerfilrecurso() {
    }

	
    public CivPerfilrecurso(CivPerfilrecursoId id, CivRecursos civRecursos, CivUsuarios civUsuarios) {
        this.id = id;
        this.civRecursos = civRecursos;
        this.civUsuarios = civUsuarios;
    }
    public CivPerfilrecurso(CivPerfilrecursoId id, CivRecursos civRecursos, CivUsuarios civUsuarios, Date perrecFechaini, Date perrecFechafin) {
       this.id = id;
       this.civRecursos = civRecursos;
       this.civUsuarios = civUsuarios;
       this.perrecFechaini = perrecFechaini;
       this.perrecFechafin = perrecFechafin;
    }
   
    public CivPerfilrecursoId getId() {
        return this.id;
    }
    
    public void setId(CivPerfilrecursoId id) {
        this.id = id;
    }
    public CivRecursos getCivRecursos() {
        return this.civRecursos;
    }
    
    public void setCivRecursos(CivRecursos civRecursos) {
        this.civRecursos = civRecursos;
    }
    public CivUsuarios getCivUsuarios() {
        return this.civUsuarios;
    }
    
    public void setCivUsuarios(CivUsuarios civUsuarios) {
        this.civUsuarios = civUsuarios;
    }
    public Date getPerrecFechaini() {
        return this.perrecFechaini;
    }
    
    public void setPerrecFechaini(Date perrecFechaini) {
        this.perrecFechaini = perrecFechaini;
    }
    public Date getPerrecFechafin() {
        return this.perrecFechafin;
    }
    
    public void setPerrecFechafin(Date perrecFechafin) {
        this.perrecFechafin = perrecFechafin;
    }




}


