package persistencias;
// Generated 7/05/2018 09:33:50 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CivRecursos generated by hbm2java
 */
public class CivRecursos  implements java.io.Serializable {


     private BigDecimal recId;
     private CivTiporecursos civTiporecursos;
     private CivPerfiles civPerfiles;
     private CivModulos civModulos;
     private CivEstadorecursos civEstadorecursos;
     private String recNombre;
     private String recDescripcion;
     private Date recFechainicial;
     private Date recFechafin;
     private String recCarpeta;
     private Set civDetalleRecUsus = new HashSet(0);
     private Set civPerfilrecursos = new HashSet(0);

    public CivRecursos() {
    }

	
    public CivRecursos(BigDecimal recId) {
        this.recId = recId;
    }
    public CivRecursos(BigDecimal recId, CivTiporecursos civTiporecursos, CivPerfiles civPerfiles, CivModulos civModulos, CivEstadorecursos civEstadorecursos, String recNombre, String recDescripcion, Date recFechainicial, Date recFechafin, String recCarpeta, Set civDetalleRecUsus, Set civPerfilrecursos) {
       this.recId = recId;
       this.civTiporecursos = civTiporecursos;
       this.civPerfiles = civPerfiles;
       this.civModulos = civModulos;
       this.civEstadorecursos = civEstadorecursos;
       this.recNombre = recNombre;
       this.recDescripcion = recDescripcion;
       this.recFechainicial = recFechainicial;
       this.recFechafin = recFechafin;
       this.recCarpeta = recCarpeta;
       this.civDetalleRecUsus = civDetalleRecUsus;
       this.civPerfilrecursos = civPerfilrecursos;
    }
   
    public BigDecimal getRecId() {
        return this.recId;
    }
    
    public void setRecId(BigDecimal recId) {
        this.recId = recId;
    }
    public CivTiporecursos getCivTiporecursos() {
        return this.civTiporecursos;
    }
    
    public void setCivTiporecursos(CivTiporecursos civTiporecursos) {
        this.civTiporecursos = civTiporecursos;
    }
    public CivPerfiles getCivPerfiles() {
        return this.civPerfiles;
    }
    
    public void setCivPerfiles(CivPerfiles civPerfiles) {
        this.civPerfiles = civPerfiles;
    }
    public CivModulos getCivModulos() {
        return this.civModulos;
    }
    
    public void setCivModulos(CivModulos civModulos) {
        this.civModulos = civModulos;
    }
    public CivEstadorecursos getCivEstadorecursos() {
        return this.civEstadorecursos;
    }
    
    public void setCivEstadorecursos(CivEstadorecursos civEstadorecursos) {
        this.civEstadorecursos = civEstadorecursos;
    }
    public String getRecNombre() {
        return this.recNombre;
    }
    
    public void setRecNombre(String recNombre) {
        this.recNombre = recNombre;
    }
    public String getRecDescripcion() {
        return this.recDescripcion;
    }
    
    public void setRecDescripcion(String recDescripcion) {
        this.recDescripcion = recDescripcion;
    }
    public Date getRecFechainicial() {
        return this.recFechainicial;
    }
    
    public void setRecFechainicial(Date recFechainicial) {
        this.recFechainicial = recFechainicial;
    }
    public Date getRecFechafin() {
        return this.recFechafin;
    }
    
    public void setRecFechafin(Date recFechafin) {
        this.recFechafin = recFechafin;
    }
    public String getRecCarpeta() {
        return this.recCarpeta;
    }
    
    public void setRecCarpeta(String recCarpeta) {
        this.recCarpeta = recCarpeta;
    }
    public Set getCivDetalleRecUsus() {
        return this.civDetalleRecUsus;
    }
    
    public void setCivDetalleRecUsus(Set civDetalleRecUsus) {
        this.civDetalleRecUsus = civDetalleRecUsus;
    }
    public Set getCivPerfilrecursos() {
        return this.civPerfilrecursos;
    }
    
    public void setCivPerfilrecursos(Set civPerfilrecursos) {
        this.civPerfilrecursos = civPerfilrecursos;
    }




}


