package persistencias;
// Generated 17/04/2018 10:23:00 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CivTipoconcepto generated by hbm2java
 */
public class CivTipoconcepto  implements java.io.Serializable {


     private BigDecimal tipconId;
     private String tipconDescripcion;
     private BigDecimal tipconEstado;
     private Date tipconFechainicial;
     private Date tipconFechafinal;
     private Set civConceptoses = new HashSet(0);

    public CivTipoconcepto() {
    }

	
    public CivTipoconcepto(BigDecimal tipconId) {
        this.tipconId = tipconId;
    }
    public CivTipoconcepto(BigDecimal tipconId, String tipconDescripcion, BigDecimal tipconEstado, Date tipconFechainicial, Date tipconFechafinal, Set civConceptoses) {
       this.tipconId = tipconId;
       this.tipconDescripcion = tipconDescripcion;
       this.tipconEstado = tipconEstado;
       this.tipconFechainicial = tipconFechainicial;
       this.tipconFechafinal = tipconFechafinal;
       this.civConceptoses = civConceptoses;
    }
   
    public BigDecimal getTipconId() {
        return this.tipconId;
    }
    
    public void setTipconId(BigDecimal tipconId) {
        this.tipconId = tipconId;
    }
    public String getTipconDescripcion() {
        return this.tipconDescripcion;
    }
    
    public void setTipconDescripcion(String tipconDescripcion) {
        this.tipconDescripcion = tipconDescripcion;
    }
    public BigDecimal getTipconEstado() {
        return this.tipconEstado;
    }
    
    public void setTipconEstado(BigDecimal tipconEstado) {
        this.tipconEstado = tipconEstado;
    }
    public Date getTipconFechainicial() {
        return this.tipconFechainicial;
    }
    
    public void setTipconFechainicial(Date tipconFechainicial) {
        this.tipconFechainicial = tipconFechainicial;
    }
    public Date getTipconFechafinal() {
        return this.tipconFechafinal;
    }
    
    public void setTipconFechafinal(Date tipconFechafinal) {
        this.tipconFechafinal = tipconFechafinal;
    }
    public Set getCivConceptoses() {
        return this.civConceptoses;
    }
    
    public void setCivConceptoses(Set civConceptoses) {
        this.civConceptoses = civConceptoses;
    }




}


