package persistencias;
// Generated 3/05/2018 09:12:03 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CivTipodeuda generated by hbm2java
 */
public class CivTipodeuda  implements java.io.Serializable {


     private BigDecimal tipdeuId;
     private CivEstadotipodeuda civEstadotipodeuda;
     private String tipdeuDescripcion;
     private Date tipdeuFechainicial;
     private Date tipdeuFechafinal;
     private String tipdeuNombrecorto;
     private BigDecimal tipdeuCodigo;
     private Set civDeudases = new HashSet(0);

    public CivTipodeuda() {
    }

	
    public CivTipodeuda(BigDecimal tipdeuId) {
        this.tipdeuId = tipdeuId;
    }
    public CivTipodeuda(BigDecimal tipdeuId, CivEstadotipodeuda civEstadotipodeuda, String tipdeuDescripcion, Date tipdeuFechainicial, Date tipdeuFechafinal, String tipdeuNombrecorto, BigDecimal tipdeuCodigo, Set civDeudases) {
       this.tipdeuId = tipdeuId;
       this.civEstadotipodeuda = civEstadotipodeuda;
       this.tipdeuDescripcion = tipdeuDescripcion;
       this.tipdeuFechainicial = tipdeuFechainicial;
       this.tipdeuFechafinal = tipdeuFechafinal;
       this.tipdeuNombrecorto = tipdeuNombrecorto;
       this.tipdeuCodigo = tipdeuCodigo;
       this.civDeudases = civDeudases;
    }
   
    public BigDecimal getTipdeuId() {
        return this.tipdeuId;
    }
    
    public void setTipdeuId(BigDecimal tipdeuId) {
        this.tipdeuId = tipdeuId;
    }
    public CivEstadotipodeuda getCivEstadotipodeuda() {
        return this.civEstadotipodeuda;
    }
    
    public void setCivEstadotipodeuda(CivEstadotipodeuda civEstadotipodeuda) {
        this.civEstadotipodeuda = civEstadotipodeuda;
    }
    public String getTipdeuDescripcion() {
        return this.tipdeuDescripcion;
    }
    
    public void setTipdeuDescripcion(String tipdeuDescripcion) {
        this.tipdeuDescripcion = tipdeuDescripcion;
    }
    public Date getTipdeuFechainicial() {
        return this.tipdeuFechainicial;
    }
    
    public void setTipdeuFechainicial(Date tipdeuFechainicial) {
        this.tipdeuFechainicial = tipdeuFechainicial;
    }
    public Date getTipdeuFechafinal() {
        return this.tipdeuFechafinal;
    }
    
    public void setTipdeuFechafinal(Date tipdeuFechafinal) {
        this.tipdeuFechafinal = tipdeuFechafinal;
    }
    public String getTipdeuNombrecorto() {
        return this.tipdeuNombrecorto;
    }
    
    public void setTipdeuNombrecorto(String tipdeuNombrecorto) {
        this.tipdeuNombrecorto = tipdeuNombrecorto;
    }
    public BigDecimal getTipdeuCodigo() {
        return this.tipdeuCodigo;
    }
    
    public void setTipdeuCodigo(BigDecimal tipdeuCodigo) {
        this.tipdeuCodigo = tipdeuCodigo;
    }
    public Set getCivDeudases() {
        return this.civDeudases;
    }
    
    public void setCivDeudases(Set civDeudases) {
        this.civDeudases = civDeudases;
    }




}


