package persistencias;
// Generated 17/04/2018 03:40:17 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * CivTablasparametricas generated by hbm2java
 */
public class CivTablasparametricas  implements java.io.Serializable {


     private BigDecimal tabparId;
     private String tabparNombretabla;
     private String tabparNombre;
     private BigDecimal tabparEstado;
     private Date tabparFechainicial;
     private Date tabparFechafinal;

    public CivTablasparametricas() {
    }

	
    public CivTablasparametricas(BigDecimal tabparId, String tabparNombretabla, String tabparNombre, BigDecimal tabparEstado, Date tabparFechainicial) {
        this.tabparId = tabparId;
        this.tabparNombretabla = tabparNombretabla;
        this.tabparNombre = tabparNombre;
        this.tabparEstado = tabparEstado;
        this.tabparFechainicial = tabparFechainicial;
    }
    public CivTablasparametricas(BigDecimal tabparId, String tabparNombretabla, String tabparNombre, BigDecimal tabparEstado, Date tabparFechainicial, Date tabparFechafinal) {
       this.tabparId = tabparId;
       this.tabparNombretabla = tabparNombretabla;
       this.tabparNombre = tabparNombre;
       this.tabparEstado = tabparEstado;
       this.tabparFechainicial = tabparFechainicial;
       this.tabparFechafinal = tabparFechafinal;
    }
   
    public BigDecimal getTabparId() {
        return this.tabparId;
    }
    
    public void setTabparId(BigDecimal tabparId) {
        this.tabparId = tabparId;
    }
    public String getTabparNombretabla() {
        return this.tabparNombretabla;
    }
    
    public void setTabparNombretabla(String tabparNombretabla) {
        this.tabparNombretabla = tabparNombretabla;
    }
    public String getTabparNombre() {
        return this.tabparNombre;
    }
    
    public void setTabparNombre(String tabparNombre) {
        this.tabparNombre = tabparNombre;
    }
    public BigDecimal getTabparEstado() {
        return this.tabparEstado;
    }
    
    public void setTabparEstado(BigDecimal tabparEstado) {
        this.tabparEstado = tabparEstado;
    }
    public Date getTabparFechainicial() {
        return this.tabparFechainicial;
    }
    
    public void setTabparFechainicial(Date tabparFechainicial) {
        this.tabparFechainicial = tabparFechainicial;
    }
    public Date getTabparFechafinal() {
        return this.tabparFechafinal;
    }
    
    public void setTabparFechafinal(Date tabparFechafinal) {
        this.tabparFechafinal = tabparFechafinal;
    }




}


