package persistencias;
// Generated 30/04/2018 08:39:48 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * CivTablasparametricas generated by hbm2java
 */
public class CivTablasparametricas  implements java.io.Serializable {


     private BigDecimal tabparId;
     private CivEstadotablasparametrica civEstadotablasparametrica;
     private String tabparNombretabla;
     private String tabparNombre;
     private Date tabparFechainicial;
     private Date tabparFechafinal;

    public CivTablasparametricas() {
    }

	
    public CivTablasparametricas(BigDecimal tabparId, CivEstadotablasparametrica civEstadotablasparametrica, String tabparNombretabla, String tabparNombre, Date tabparFechainicial) {
        this.tabparId = tabparId;
        this.civEstadotablasparametrica = civEstadotablasparametrica;
        this.tabparNombretabla = tabparNombretabla;
        this.tabparNombre = tabparNombre;
        this.tabparFechainicial = tabparFechainicial;
    }
    public CivTablasparametricas(BigDecimal tabparId, CivEstadotablasparametrica civEstadotablasparametrica, String tabparNombretabla, String tabparNombre, Date tabparFechainicial, Date tabparFechafinal) {
       this.tabparId = tabparId;
       this.civEstadotablasparametrica = civEstadotablasparametrica;
       this.tabparNombretabla = tabparNombretabla;
       this.tabparNombre = tabparNombre;
       this.tabparFechainicial = tabparFechainicial;
       this.tabparFechafinal = tabparFechafinal;
    }
   
    public BigDecimal getTabparId() {
        return this.tabparId;
    }
    
    public void setTabparId(BigDecimal tabparId) {
        this.tabparId = tabparId;
    }
    public CivEstadotablasparametrica getCivEstadotablasparametrica() {
        return this.civEstadotablasparametrica;
    }
    
    public void setCivEstadotablasparametrica(CivEstadotablasparametrica civEstadotablasparametrica) {
        this.civEstadotablasparametrica = civEstadotablasparametrica;
    }
    public String getTabparNombretabla() {
        return this.tabparNombretabla;
    }
    
    public void setTabparNombretabla(String tabparNombretabla) {
        this.tabparNombretabla = tabparNombretabla;
    }
    public String getTabparNombre() {
        return this.tabparNombre;
    }
    
    public void setTabparNombre(String tabparNombre) {
        this.tabparNombre = tabparNombre;
    }
    public Date getTabparFechainicial() {
        return this.tabparFechainicial;
    }
    
    public void setTabparFechainicial(Date tabparFechainicial) {
        this.tabparFechainicial = tabparFechainicial;
    }
    public Date getTabparFechafinal() {
        return this.tabparFechafinal;
    }
    
    public void setTabparFechafinal(Date tabparFechafinal) {
        this.tabparFechafinal = tabparFechafinal;
    }




}


