package persistencias;
// Generated 3/05/2018 09:12:03 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CivTiporecursos generated by hbm2java
 */
public class CivTiporecursos  implements java.io.Serializable {


     private BigDecimal tiprecId;
     private CivEstadotiporecursos civEstadotiporecursos;
     private String tiprecDescripcion;
     private Date tiprecFechafinal;
     private Date tiprecFechainicial;
     private String tiprecNombrecorto;
     private BigDecimal tiprecCodigo;
     private Set civRecursoses = new HashSet(0);

    public CivTiporecursos() {
    }

	
    public CivTiporecursos(BigDecimal tiprecId) {
        this.tiprecId = tiprecId;
    }
    public CivTiporecursos(BigDecimal tiprecId, CivEstadotiporecursos civEstadotiporecursos, String tiprecDescripcion, Date tiprecFechafinal, Date tiprecFechainicial, String tiprecNombrecorto, BigDecimal tiprecCodigo, Set civRecursoses) {
       this.tiprecId = tiprecId;
       this.civEstadotiporecursos = civEstadotiporecursos;
       this.tiprecDescripcion = tiprecDescripcion;
       this.tiprecFechafinal = tiprecFechafinal;
       this.tiprecFechainicial = tiprecFechainicial;
       this.tiprecNombrecorto = tiprecNombrecorto;
       this.tiprecCodigo = tiprecCodigo;
       this.civRecursoses = civRecursoses;
    }
   
    public BigDecimal getTiprecId() {
        return this.tiprecId;
    }
    
    public void setTiprecId(BigDecimal tiprecId) {
        this.tiprecId = tiprecId;
    }
    public CivEstadotiporecursos getCivEstadotiporecursos() {
        return this.civEstadotiporecursos;
    }
    
    public void setCivEstadotiporecursos(CivEstadotiporecursos civEstadotiporecursos) {
        this.civEstadotiporecursos = civEstadotiporecursos;
    }
    public String getTiprecDescripcion() {
        return this.tiprecDescripcion;
    }
    
    public void setTiprecDescripcion(String tiprecDescripcion) {
        this.tiprecDescripcion = tiprecDescripcion;
    }
    public Date getTiprecFechafinal() {
        return this.tiprecFechafinal;
    }
    
    public void setTiprecFechafinal(Date tiprecFechafinal) {
        this.tiprecFechafinal = tiprecFechafinal;
    }
    public Date getTiprecFechainicial() {
        return this.tiprecFechainicial;
    }
    
    public void setTiprecFechainicial(Date tiprecFechainicial) {
        this.tiprecFechainicial = tiprecFechainicial;
    }
    public String getTiprecNombrecorto() {
        return this.tiprecNombrecorto;
    }
    
    public void setTiprecNombrecorto(String tiprecNombrecorto) {
        this.tiprecNombrecorto = tiprecNombrecorto;
    }
    public BigDecimal getTiprecCodigo() {
        return this.tiprecCodigo;
    }
    
    public void setTiprecCodigo(BigDecimal tiprecCodigo) {
        this.tiprecCodigo = tiprecCodigo;
    }
    public Set getCivRecursoses() {
        return this.civRecursoses;
    }
    
    public void setCivRecursoses(Set civRecursoses) {
        this.civRecursoses = civRecursoses;
    }




}


