package persistencias;
// Generated 17/04/2018 10:23:00 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CivUsuarios generated by hbm2java
 */
public class CivUsuarios  implements java.io.Serializable {


     private BigDecimal usuId;
     private CivPersonas civPersonas;
     private String usuNombre;
     private String usuPassword;
     private BigDecimal usuEstado;
     private Date usuFechainicial;
     private Date usuFechafinal;
     private Date usuFechaproceso;
     private Set civAttemptses = new HashSet(0);
     private Set civProcesosjuridicoses = new HashSet(0);
     private Set civDeudases = new HashSet(0);
     private Set civUspHistorias = new HashSet(0);
     private Set civPerfilrecursos = new HashSet(0);
     private Set civDetalleRecUsus = new HashSet(0);
     private Set civDetalleProcesojuridicos = new HashSet(0);

    public CivUsuarios() {
    }

	
    public CivUsuarios(BigDecimal usuId, CivPersonas civPersonas, String usuNombre, String usuPassword, BigDecimal usuEstado, Date usuFechainicial, Date usuFechaproceso) {
        this.usuId = usuId;
        this.civPersonas = civPersonas;
        this.usuNombre = usuNombre;
        this.usuPassword = usuPassword;
        this.usuEstado = usuEstado;
        this.usuFechainicial = usuFechainicial;
        this.usuFechaproceso = usuFechaproceso;
    }
    public CivUsuarios(BigDecimal usuId, CivPersonas civPersonas, String usuNombre, String usuPassword, BigDecimal usuEstado, Date usuFechainicial, Date usuFechafinal, Date usuFechaproceso, Set civAttemptses, Set civProcesosjuridicoses, Set civDeudases, Set civUspHistorias, Set civPerfilrecursos, Set civDetalleRecUsus, Set civDetalleProcesojuridicos) {
       this.usuId = usuId;
       this.civPersonas = civPersonas;
       this.usuNombre = usuNombre;
       this.usuPassword = usuPassword;
       this.usuEstado = usuEstado;
       this.usuFechainicial = usuFechainicial;
       this.usuFechafinal = usuFechafinal;
       this.usuFechaproceso = usuFechaproceso;
       this.civAttemptses = civAttemptses;
       this.civProcesosjuridicoses = civProcesosjuridicoses;
       this.civDeudases = civDeudases;
       this.civUspHistorias = civUspHistorias;
       this.civPerfilrecursos = civPerfilrecursos;
       this.civDetalleRecUsus = civDetalleRecUsus;
       this.civDetalleProcesojuridicos = civDetalleProcesojuridicos;
    }
   
    public BigDecimal getUsuId() {
        return this.usuId;
    }
    
    public void setUsuId(BigDecimal usuId) {
        this.usuId = usuId;
    }
    public CivPersonas getCivPersonas() {
        return this.civPersonas;
    }
    
    public void setCivPersonas(CivPersonas civPersonas) {
        this.civPersonas = civPersonas;
    }
    public String getUsuNombre() {
        return this.usuNombre;
    }
    
    public void setUsuNombre(String usuNombre) {
        this.usuNombre = usuNombre;
    }
    public String getUsuPassword() {
        return this.usuPassword;
    }
    
    public void setUsuPassword(String usuPassword) {
        this.usuPassword = usuPassword;
    }
    public BigDecimal getUsuEstado() {
        return this.usuEstado;
    }
    
    public void setUsuEstado(BigDecimal usuEstado) {
        this.usuEstado = usuEstado;
    }
    public Date getUsuFechainicial() {
        return this.usuFechainicial;
    }
    
    public void setUsuFechainicial(Date usuFechainicial) {
        this.usuFechainicial = usuFechainicial;
    }
    public Date getUsuFechafinal() {
        return this.usuFechafinal;
    }
    
    public void setUsuFechafinal(Date usuFechafinal) {
        this.usuFechafinal = usuFechafinal;
    }
    public Date getUsuFechaproceso() {
        return this.usuFechaproceso;
    }
    
    public void setUsuFechaproceso(Date usuFechaproceso) {
        this.usuFechaproceso = usuFechaproceso;
    }
    public Set getCivAttemptses() {
        return this.civAttemptses;
    }
    
    public void setCivAttemptses(Set civAttemptses) {
        this.civAttemptses = civAttemptses;
    }
    public Set getCivProcesosjuridicoses() {
        return this.civProcesosjuridicoses;
    }
    
    public void setCivProcesosjuridicoses(Set civProcesosjuridicoses) {
        this.civProcesosjuridicoses = civProcesosjuridicoses;
    }
    public Set getCivDeudases() {
        return this.civDeudases;
    }
    
    public void setCivDeudases(Set civDeudases) {
        this.civDeudases = civDeudases;
    }
    public Set getCivUspHistorias() {
        return this.civUspHistorias;
    }
    
    public void setCivUspHistorias(Set civUspHistorias) {
        this.civUspHistorias = civUspHistorias;
    }
    public Set getCivPerfilrecursos() {
        return this.civPerfilrecursos;
    }
    
    public void setCivPerfilrecursos(Set civPerfilrecursos) {
        this.civPerfilrecursos = civPerfilrecursos;
    }
    public Set getCivDetalleRecUsus() {
        return this.civDetalleRecUsus;
    }
    
    public void setCivDetalleRecUsus(Set civDetalleRecUsus) {
        this.civDetalleRecUsus = civDetalleRecUsus;
    }
    public Set getCivDetalleProcesojuridicos() {
        return this.civDetalleProcesojuridicos;
    }
    
    public void setCivDetalleProcesojuridicos(Set civDetalleProcesojuridicos) {
        this.civDetalleProcesojuridicos = civDetalleProcesojuridicos;
    }




}


