package persistencias;
// Generated 17/04/2018 03:40:17 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * CivUspHistoria generated by hbm2java
 */
public class CivUspHistoria  implements java.io.Serializable {


     private BigDecimal id;
     private CivUsuarios civUsuarios;
     private String PData;
     private Date fechaProceso;
     private BigDecimal estado;

    public CivUspHistoria() {
    }

	
    public CivUspHistoria(BigDecimal id) {
        this.id = id;
    }
    public CivUspHistoria(BigDecimal id, CivUsuarios civUsuarios, String PData, Date fechaProceso, BigDecimal estado) {
       this.id = id;
       this.civUsuarios = civUsuarios;
       this.PData = PData;
       this.fechaProceso = fechaProceso;
       this.estado = estado;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public CivUsuarios getCivUsuarios() {
        return this.civUsuarios;
    }
    
    public void setCivUsuarios(CivUsuarios civUsuarios) {
        this.civUsuarios = civUsuarios;
    }
    public String getPData() {
        return this.PData;
    }
    
    public void setPData(String PData) {
        this.PData = PData;
    }
    public Date getFechaProceso() {
        return this.fechaProceso;
    }
    
    public void setFechaProceso(Date fechaProceso) {
        this.fechaProceso = fechaProceso;
    }
    public BigDecimal getEstado() {
        return this.estado;
    }
    
    public void setEstado(BigDecimal estado) {
        this.estado = estado;
    }




}


